### ISSUE TITLE
Web site is only one page

### ISSUE THREAD

**Issue by Shadrock** [LianMingshuang/Lianmingshuang.github.io#1]
Hi Mingshuang,
Your website looks pretty good: I appreciate that you've made some different color and font choices and included titles for all of your maps! However, this is only one web page: did you have trouble creating the blog pages or did you decide to get rid of them for design purposes?

**Comment by LianMingshuang** [comment]
Hi Shadrock,
Sorry about this. I did not notice that we need to create many pages in the guild line before. And I think there are only four parts needed to be combined. So, one web page is enough. Maybe it will be short and clear to reduce the number of jumps. Luckily, I have no trouble adding some pages. I will improve my website. Thank you.

**Comment by Shadrock** [comment]
It's okay, Mingshuang. This is fine for now (you got an A!). I just wanted to check in and make sure it wasn't a technical problem.
